// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLiYF0vHtlW_l4nUEQX7aVxEGllydi6u4',
    appId: '1:94855135619:web:df2f7f2cea7944517b76b6',
    messagingSenderId: '94855135619',
    projectId: 'conclavegpt-6ac77',
    authDomain: 'conclavegpt-6ac77.firebaseapp.com',
    storageBucket: 'conclavegpt-6ac77.firebasestorage.app',
    measurementId: 'G-Y7M06GPSRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiZtyzvbvnp3tUvqJgViJaa_8oPdlbDGI',
    appId: '1:94855135619:android:5a4f532bb277f9367b76b6',
    messagingSenderId: '94855135619',
    projectId: 'conclavegpt-6ac77',
    storageBucket: 'conclavegpt-6ac77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGrNUTasco05mpr71AqnBuJ9F0UE4fNI',
    appId: '1:94855135619:ios:9f082cfd34448c507b76b6',
    messagingSenderId: '94855135619',
    projectId: 'conclavegpt-6ac77',
    storageBucket: 'conclavegpt-6ac77.firebasestorage.app',
    iosBundleId: 'com.example.conclavegpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnGrNUTasco05mpr71AqnBuJ9F0UE4fNI',
    appId: '1:94855135619:ios:9f082cfd34448c507b76b6',
    messagingSenderId: '94855135619',
    projectId: 'conclavegpt-6ac77',
    storageBucket: 'conclavegpt-6ac77.firebasestorage.app',
    iosBundleId: 'com.example.conclavegpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLiYF0vHtlW_l4nUEQX7aVxEGllydi6u4',
    appId: '1:94855135619:web:b3a3e2df472e375a7b76b6',
    messagingSenderId: '94855135619',
    projectId: 'conclavegpt-6ac77',
    authDomain: 'conclavegpt-6ac77.firebaseapp.com',
    storageBucket: 'conclavegpt-6ac77.firebasestorage.app',
    measurementId: 'G-VLBB98M3TJ',
  );
}
